blank_issues_enabled: false

contact_links:
- name: Chat ğŸ’¬
  url: https://adoptium.net/slack.html
  about: "Join our Slack channel #support to get help diagnosing your problems."

- name: Docker ğŸ‹
  url: https://github.com/adoptium/containers/issues/new
  about: "Please report issues with the `eclipse-temurin` Docker images here."

- name: JDK Bug System â˜•
  url: https://bugs.openjdk.java.net/secure/Dashboard.jspa
  about: You can search for known bugs in the JDK Bug System.
