blank_issues_enabled: false

contact_links:
  - name: Minecraft Java Edition Related Issue ğŸ”
    url: https://bugs.mojang.com/projects/MC/summary
    about: Please submit Minecraft Java Edition related issues to the Mojang Issue Tracker First :-).

  - name: Chat ğŸ’¬
    url: https://adoptium.net/slack
    about: "Join our Slack channel #support to get help diagnosing your problems."

  - name: Docker ğŸ‹
    url: https://github.com/adoptium/containers/issues/new
    about: "Please report issues with the `eclipse-temurin` Docker images here."

  - name: JDK Bug System â˜•
    url: https://bugs.openjdk.java.net/secure/Dashboard.jspa
    about: You can search for known bugs in the JDK Bug System.
